# Generated by Django 6.0.2 on 2026-02-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('available_for_volunteers', models.BooleanField(default=False)),
                ('available_for_adoption', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='pets')),
                ('caretakers', models.ManyToManyField(blank=True, to='accounts.caretaker')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('activity_type', models.CharField(choices=[('walk', 'Walk'), ('play', 'Play'), ('training', 'Training')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.volunteer')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
