# Generated by Django 6.0.2 on 2026-02-22 14:25

import django.db.models.deletion
import django.utils.timezone
import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('available_for_volunteers', models.BooleanField(default=False)),
                ('available_for_adoption', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to=pets.models.pet_image_upload_to)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True, default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('activity_type', models.CharField(choices=[('walk', 'Walk'), ('play', 'Play'), ('training', 'Training')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.volunteer')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetCaretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.caretaker')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='caretakers',
            field=models.ManyToManyField(blank=True, through='pets.PetCaretaker', to='accounts.caretaker'),
        ),
        migrations.AddConstraint(
            model_name='petcaretaker',
            constraint=models.UniqueConstraint(fields=('pet', 'caretaker'), name='uniq_pet_caretaker'),
        ),
    ]
