# Generated by Django 6.0.2 on 2026-04-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pets', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter'),
        ),
        migrations.AddField(
            model_name='petcaretaker',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.caretaker'),
        ),
        migrations.AddField(
            model_name='petcaretaker',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
        migrations.AddField(
            model_name='pet',
            name='caretakers',
            field=models.ManyToManyField(blank=True, through='pets.PetCaretaker', to='accounts.caretaker'),
        ),
        migrations.AddConstraint(
            model_name='petcaretaker',
            constraint=models.UniqueConstraint(fields=('pet', 'caretaker'), name='uniq_pet_caretaker'),
        ),
    ]
