# Generated by Django 6.0.2 on 2026-02-20 22:31

import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, upload_to=pets.models.pet_image_upload_to),
        ),
    ]
