# Generated by Django 6.0.2 on 2026-02-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_created_at_alter_pet_modified_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
