# Generated by Django 6.0.2 on 2026-02-22 14:25

import django.utils.timezone
import shelters.models
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=shelters.models.shelter_image_upload_to)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True, default=django.utils.timezone.now)),
                ('caretakers', models.ManyToManyField(blank=True, related_name='shelters', to='accounts.caretaker')),
            ],
        ),
        migrations.AddField(
            model_name='shelter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
