# Generated by Django 6.0.2 on 2026-04-04 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='staffed_shelters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelterdashboard',
            name='shelter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard',
                                       to='shelters.shelter'),
        ),
    ]
