# Generated by Django 6.0.2 on 2026-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
