# Generated by Django 6.0.2 on 2026-02-20 22:31

import shelters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='image',
            field=models.ImageField(blank=True, upload_to=shelters.models.shelter_image_upload_to),
        ),
    ]
