# Generated by Django 6.0.2 on 2026-03-29 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shelters', '0002_alter_shelter_created_at_alter_shelter_modified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='staffed_shelters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShelterDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('priorities', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard',
                                                 to='shelters.shelter')),
            ],
        ),
    ]
