# Generated by Django 6.0.2 on 2026-04-04 16:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to=accounts.models.account_image_upload_to)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.CharField(
                    choices=[('behavior', 'Behavior'), ('medical', 'Medical'), ('nutrition', 'Nutrition')],
                    max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to=accounts.models.account_image_upload_to)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('experience_level', models.CharField(
                    choices=[('beginner', 'Beginner (Tier 1)'), ('intermediate', 'Intermediate (Tier 2)'),
                             ('advanced', 'Advanced (Tier 3)')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
