# Generated by Django 6.0.2 on 2026-02-20 22:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='image',
            field=models.ImageField(blank=True, upload_to=accounts.models.account_image_upload_to),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, upload_to=accounts.models.account_image_upload_to),
        ),
    ]
