# Generated by Django 6.0.2 on 2026-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='specialization',
            field=models.CharField(choices=[('behavior', 'Behavior'), ('medical', 'Medical'), ('nutrition', 'Nutrition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner (Tier 1)'), ('intermediate', 'Intermediate (Tier 2)'), ('advanced', 'Advanced (Tier 3)')], max_length=20),
        ),
    ]
