# Generated by Django 6.0.2 on 2026-04-05 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[
                django.core.validators.RegexValidator(message='Enter a valid phone number in format +359XXXXXXXXX.',
                                                      regex='^\\+359\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[
                django.core.validators.RegexValidator(message='Enter a valid phone number in format +359XXXXXXXXX.',
                                                      regex='^\\+359\\d{9}$')]),
        ),
    ]
