# Generated by Django 6.0.2 on 2026-03-29 21:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0002_alter_caretaker_specialization_and_more'),
        ('pets', '0003_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('missed', 'Missed')],
                                            default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('caretaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                related_name='feeding_tasks', to='accounts.caretaker')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_tasks',
                                          to='pets.pet')),
            ],
            options={
                'ordering': ['-scheduled_for', '-id'],
            },
        ),
    ]
